version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env.example
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
